version: '3.8'

services:
  earnapp:
    image: earnapp/earnapp:latest
    container_name: ${INSTANCE_NAME:-earnapp_instance}
    restart: unless-stopped
    network_mode: service:proxy
    environment:
      - UUID=${INSTANCE_UUID}
      - PROXY_ENABLED=${PROXY_ENABLED:-false}
      - PROXY_HOST=${PROXY_HOST:-}
      - PROXY_PORT=${PROXY_PORT:-}
      - PROXY_USERNAME=${PROXY_USERNAME:-}
      - PROXY_PASSWORD=${PROXY_PASSWORD:-}
    deploy:
      resources:
        limits:
          cpus: ${APP_CPU_LIMIT:-0.5}
          memory: ${APP_MEM_LIMIT:-2G}
        reservations:
          memory: ${APP_MEM_RESERV:-1G}

  proxy:
    image: nginx:alpine
    container_name: ${INSTANCE_NAME:-earnapp_instance}_proxy
    restart: unless-stopped
    ports:
      - "${M4B_DASHBOARD_PORT:-8081}:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: ${PROXY_CPU_LIMIT:-0.2}
          memory: ${PROXY_MEM_LIMIT:-512M}
        reservations:
          memory: ${PROXY_MEM_RESERV:-256M}

  watchtower:
    image: containrrr/watchtower:latest
    container_name: ${INSTANCE_NAME:-earnapp_instance}_watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
    environment:
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL:-}
    deploy:
      resources:
        limits:
          cpus: ${WATCHTOWER_CPU_LIMIT:-0.1}
          memory: ${WATCHTOWER_MEM_LIMIT:-256M}
        reservations:
          memory: ${WATCHTOWER_MEM_RESERV:-128M}

  dashboard:
    image: money4band/dashboard:latest
    container_name: ${INSTANCE_NAME:-earnapp_instance}_dashboard
    restart: unless-stopped
    ports:
      - "${M4B_DASHBOARD_PORT:-8081}:80"
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME:-earnapp_instance}
      - INSTANCE_UUID=${INSTANCE_UUID}
      - PROXY_ENABLED=${PROXY_ENABLED:-false}
    deploy:
      resources:
        limits:
          cpus: ${DASHBOARD_CPU_LIMIT:-0.3}
          memory: ${DASHBOARD_MEM_LIMIT:-512M}
        reservations:
          memory: ${DASHBOARD_MEM_RESERV:-256M} 